package:
  name: scippuncertainty
  version: {{ GIT_DESCRIBE_TAG }}
source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.8
    - scipp>=23.01.1

test:
  imports:
    - scippuncertainty
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest tests

build:
  noarch: python
  script:
    - pip install .

about:
  home: https://github.com/scipp/scippuncertainty
  license: BSD-3-Clause
  summary: Advanced uncertainty propagation with Scipp
  description: Advanced uncertainty propagation with Scipp
  dev_url: https://github.com/scipp/scippuncertainty
  doc_url: https://scipp.github.io/scippuncertainty
