package:
  name: scippuncertainty

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.10

  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package }}{% endif %}
  {% endfor %}

test:
  imports:
    - scippuncertainty
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/scippuncertainty
  license: BSD-3-Clause
  summary: Advanced uncertainty propagation with Scipp
  description: Advanced uncertainty propagation with Scipp
  dev_url: https://github.com/scipp/scippuncertainty
  doc_url: https://scipp.github.io/scippuncertainty
